### PR TITLE
Miscellaneous minor formatting tweaks, and one consistency fix

### PR DESCRIPTION
**Pull request by jonahgreenthal**

### CODE REVIEW

**Comment by puls** [comment]
This appears to include the code for #70.

**Comment by jonahgreenthal** [comment]
Probably because I don't know how to use Git properly. What should I do?

**Comment by jonahgreenthal** [comment]
Thanks — onto this one!

**Comment by jonahgreenthal** [comment]
What do we need to do to get this merged?

**Comment by puls** [comment]
I think you need to rebase this against the latest `quizbowl/gh-pages`.

**Pull request merged**
